# Accessing Data within Pandas

In [4]:
import pandas as pd

In [6]:
# import data from the scikit-learn library

from sklearn.datasets import load_wine

data = load_wine()
df = pd.DataFrame(data.data, columns=data.feature_names)

In [7]:
#reading the first 10 entries in the data
df.head(10)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0

### Methods and attributes to access the data information

These methods include the .head() that extracts the top attributes and .tail() that extracts the last attributes and the .info() that extracts a concise summary of the dataframe

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
#the tail end of the data the last 5 rows

df.tail(5)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560.0

In [10]:
# the info of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB

In [14]:
# Using .index, you can access the index or row labels of the DataFrame

df.index

RangeIndex(start=0, stop=178, step=1)

In [16]:
df.columns  # this accesses the columns of the data

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [17]:
df.dtypes  # Shows the data types of all the columns of the dataframe

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
dtype: object

In [19]:
df.shape #shows the dimensions of the data i.e (rows,columns)

(178, 13)

### Selecting the DataFrame information
The attributes for this are :
-    .iloc, this is used to locate the row of the data based on the index given
-    .loc, this has 2 use cases:
-                  Selecting by label/index
                   Selecting with boolean / conditional look up

In [21]:
# iloc

df.iloc[3]

alcohol                           14.37
malic_acid                         1.95
ash                                2.50
alcalinity_of_ash                 16.80
magnesium                        113.00
total_phenols                      3.85
flavanoids                         3.49
nonflavanoid_phenols               0.24
proanthocyanins                    2.18
color_intensity                    7.80
hue                                0.86
od280/od315_of_diluted_wines       3.45
proline                         1480.00
Name: 3, dtype: float64

In [28]:
# in cases where you want to select multiple rows u an use colons for that

df.iloc[1:8]  #similar to how it is done in lists

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0

In [32]:
# you can use the , to perform column selection based on index as well

df.iloc[:,3:7]

     alcalinity_of_ash  magnesium  total_phenols  flavanoids
0                 15.6      127.0           2.80        3.06
1                 11.2      100.0           2.65        2.76
2                 18.6      101.0           2.80        3.24
3                 16.8      113.0           3.85        3.49
4                 21.0      118.0           2.80        2.69
..                 ...        ...            ...         ...
173               20.5       95.0           1.68        0.61
174               23.0      102.0           1.80        0.75
175               20.0      120.0           1.59        0.69
176               20.0      120.0           1.65        0.68
177               24.5       96.0           2.05        0.76

[178 rows x 4 columns]

In [39]:
# given this information you can perform row and column seection at the same time

df.iloc[5:10,3:9]

,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins
5,15.2,112.0,3.27,3.39,0.34,1.97
6,14.6,96.0,2.50,2.52,0.30,1.98
7,17.6,121.0,2.60,2.51,0.31,1.25
8,14.0,97.0,2.80,2.98,0.29,1.98
9,16.0,98.0,2.98,3.15,0.22,1.85

### `.loc`

In [34]:
# label based indexing

df.loc[:,"magnesium"]

0      127.0
1      100.0
2      101.0
3      113.0
4      118.0
       ...
173     95.0
174    102.0
175    120.0
176    120.0
177     96.0
Name: magnesium, Length: 178, dtype: float64

In [79]:
df.loc[7:16,["magnesium","total_phenols"]]

    magnesium  total_phenols
7       121.0           2.60
8        97.0           2.80
9        98.0           2.98
10      105.0           2.95
11       95.0           2.20
12       89.0           2.60
13       91.0           3.10
14      102.0           3.30
15      112.0           2.85
16      120.0           2.80

### boolean indexing using the .loc

in the case below imagine you'd like to create a new DataFrame that only contains the wines with an alcohol percentage below 12. This can be done as follows:

In [42]:

df.loc[df['alcohol'] < 12]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
74,11.96,1.09,2.30,21.0,101.0,3.38,2.14,0.13,1.65,3.21,0.99,3.13,886.0
75,11.66,1.88,1.92,16.0,97.0,1.61,1.57,0.34,1.15,3.80,1.23,2.14,428.0
77,11.84,2.89,2.23,18.0,112.0,1.72,1.32,0.43,0.95,2.65,0.96,2.52,500.0
84,11.84,0.89,2.58,18.0,94.0,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520.0
87,11.65,1.67,2.62,26.0,88.0,1.92,1.61,0.40,1.34,2.60,1.36,3.21,562.0
88,11.64,2.06,2.46,21.6,84.0,1.95,1.69,0.48,1.35,2.80,1.00,2.75,680.0
94,11.62,1.99,2.28,18.0,98.0,3.02,2.26,0.17,1.35,3.25,1.16,2.96,345.0
96,11.81,2.12,2.74,21.5,134.0,1.60,0.99,0.14,1.56,2.50,0.95,2.26,625.0
103,11.82,1.72,1.88,19.5,86.0,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415.0
109,11.61,1.35,2.70,20.0,94.0,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680.0
110,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0
112,11.76,2.68,2.92,20.0,103.0,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607.0
113,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0
115,11.03,1.51,2.20,21.5,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0
116,11.82,1.47,1.99,20.8,86.0,1.98,1.60,0.30,1.53,1.95,0.95,3.33,495.0
120,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0
121,11.56,2.05,3.23,28.5,119.0,3.18,5.08,0.47,1.87,6.00,0.93,3.69,465.0
124,11.87,4.31,2.39,21.0,82.0,2.86,3.03,0.21,2.91,2.80,0.75,3.64,380.0
127,11.79,2.13,2.78,28.5,92.0,2.13,2.24,0.58,1.76,3.00,0.97,2.44,466.0

In [43]:
# the above can be done using :
df[df['alcohol'] < 12]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
74,11.96,1.09,2.30,21.0,101.0,3.38,2.14,0.13,1.65,3.21,0.99,3.13,886.0
75,11.66,1.88,1.92,16.0,97.0,1.61,1.57,0.34,1.15,3.80,1.23,2.14,428.0
77,11.84,2.89,2.23,18.0,112.0,1.72,1.32,0.43,0.95,2.65,0.96,2.52,500.0
84,11.84,0.89,2.58,18.0,94.0,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520.0
87,11.65,1.67,2.62,26.0,88.0,1.92,1.61,0.40,1.34,2.60,1.36,3.21,562.0
88,11.64,2.06,2.46,21.6,84.0,1.95,1.69,0.48,1.35,2.80,1.00,2.75,680.0
94,11.62,1.99,2.28,18.0,98.0,3.02,2.26,0.17,1.35,3.25,1.16,2.96,345.0
96,11.81,2.12,2.74,21.5,134.0,1.60,0.99,0.14,1.56,2.50,0.95,2.26,625.0
103,11.82,1.72,1.88,19.5,86.0,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415.0
109,11.61,1.35,2.70,20.0,94.0,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680.0
110,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0
112,11.76,2.68,2.92,20.0,103.0,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607.0
113,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0
115,11.03,1.51,2.20,21.5,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0
116,11.82,1.47,1.99,20.8,86.0,1.98,1.60,0.30,1.53,1.95,0.95,3.33,495.0
120,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0
121,11.56,2.05,3.23,28.5,119.0,3.18,5.08,0.47,1.87,6.00,0.93,3.69,465.0
124,11.87,4.31,2.39,21.0,82.0,2.86,3.03,0.21,2.91,2.80,0.75,3.64,380.0
127,11.79,2.13,2.78,28.5,92.0,2.13,2.24,0.58,1.76,3.00,0.97,2.44,466.0

In [47]:
df.loc[df["alcohol"]<12,['color_intensity']]

     color_intensity
74              3.21
75              3.80
77              2.65
84              3.05
87              2.60
88              2.80
94              3.25
96              2.50
103             2.06
109             2.65
110             2.90
112             3.80
113             3.08
115             1.90
116             1.95
120             3.25
121             6.00
124             2.80
127             3.00

### Selectors for series

In [51]:
#creating series from one column dataframes 

col_intensity = df["color_intensity"]

type(col_intensity)

pandas.core.series.Series

In [58]:
col_intensity[:5]

0    5.64
1    4.38
2    5.68
3    7.80
4    4.32
Name: color_intensity, dtype: float64

In [60]:
col_intensity[col_intensity >= 8]

18      8.700000
49      8.900000
144     8.210000
148     8.420000
149     9.400000
150     8.600000
151    10.800000
153    10.520000
156     9.010000
158    13.000000
159    11.750000
164     9.580000
166    10.680000
167    10.260000
168     8.660000
169     8.500000
171     9.899999
172     9.700000
175    10.200000
176     9.300000
177     9.200000
Name: color_intensity, dtype: float64

### Changing the values and setting values in DataFrames and Series

In [66]:

# Changing the values in instances where we want to set values for a certain reason
df.loc[df["color_intensity"] > 10 , 'color_intensity'] = 10
# df.loc[df["color_intensity"] >10]
df["color_intensity"]

0       5.64
1       4.38
2       5.68
3       7.80
4       4.32
       ...
173     7.70
174     7.30
175    10.00
176     9.30
177     9.20
Name: color_intensity, Length: 178, dtype: float64

In [73]:
#creating new columns in this case a column called shade

df.loc[df["color_intensity"] > 7, "shade"] = "dark"
df.loc[df["color_intensity"] <= 7, "shade"] = "light"

df["shade"]

0      light
1      light
2      light
3       dark
4      light
       ...
173     dark
174     dark
175     dark
176     dark
177     dark
Name: shade, Length: 178, dtype: object

In [75]:
df[df["shade"] == "dark"]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,shade
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.800000,0.86,3.45,1480.0,dark
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.220000,1.01,3.55,1045.0,dark
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.500000,1.20,3.00,1547.0,dark
15,13.63,1.81,2.70,17.2,112.0,2.85,2.91,0.30,1.46,7.300000,1.28,2.88,1310.0,dark
18,14.19,1.59,2.48,16.5,108.0,3.30,3.93,0.32,1.86,8.700000,1.23,2.82,1680.0,dark
49,13.94,1.73,2.27,17.4,108.0,2.88,3.54,0.32,2.08,8.900000,1.12,3.10,1260.0,dark
50,13.05,1.73,2.04,12.4,92.0,2.72,3.27,0.17,2.91,7.200000,1.12,2.91,1150.0,dark
52,13.82,1.75,2.42,14.0,111.0,3.88,3.74,0.32,1.87,7.050000,1.01,3.26,1190.0,dark
135,12.60,2.46,2.20,18.5,94.0,1.62,0.66,0.63,0.94,7.100000,0.73,1.58,695.0,dark
144,12.25,3.88,2.20,18.5,112.0,1.38,0.78,0.29,1.14,8.210000,0.65,2.00,855.0,dark
147,12.87,4.61,2.48,21.5,86.0,1.70,0.65,0.47,0.86,7.650000,0.54,1.86,625.0,dark
148,13.32,3.24,2.38,21.5,92.0,1.93,0.76,0.45,1.25,8.420000,0.55,1.62,650.0,dark
149,13.08,3.90,2.36,21.5,113.0,1.41,1.39,0.34,1.14,9.400000,0.57,1.33,550.0,dark
150,13.50,3.12,2.62,24.0,123.0,1.40,1.57,0.22,1.25,8.600000,0.59,1.30,500.0,dark
151,12.79,2.67,2.48,22.0,112.0,1.48,1.36,0.24,1.26,10.000000,0.48,1.47,480.0,dark
152,13.11,1.90,2.75,25.5,116.0,2.20,1.28,0.26,1.56,7.100000,0.61,1.33,425.0,dark
153,13.23,3.30,2.28,18.5,98.0,1.80,0.83,0.61,1.87,10.000000,0.56,1.51,675.0,dark
154,12.58,1.29,2.10,20.0,103.0,1.48,0.58,0.53,1.40,7.600000,0.58,1.55,640.0,dark
155,13.17,5.19,2.32,22.0,93.0,1.74,0.63,0.61,1.55,7.900000,0.60,1.48,725.0,dark
156,13.84,4.12,2.38,19.5,89.0,1.80,0.83,0.48,1.56,9.010000,0.57,1.64,480.0,dark
157,12.45,3.03,2.64,27.0,97.0,1.90,0.58,0.63,1.14,7.500000,0.67,1.73,880.0,dark
158,14.34,1.68,2.70,25.0,98.0,2.80,1.31,0.53,2.70,10.000000,0.57,1.96,660.0,dark
159,13.48,1.67,2.64,22.5,89.0,2.60,1.10,0.52,2.29,10.000000,0.57,1.78,620.0,dark
160,12.36,3.83,2.38,21.0,88.0,2.30,0.92,0.50,1.04,7.650000,0.56,1.58,520.0,dark
164,13.78,2.76,2.30,22.0,90.0,1.35,0.68,0.41,1.03,9.580000,0.70,1.68,615.0,dark
166,13.45,3.70,2.60,23.0,111.0,1.70,0.92,0.43,1.46,10.000000,0.85,1.56,695.0,dark
167,12.82,3.37,2.30,19.5,88.0,1.48,0.66,0.40,0.97,10.000000,0.72,1.75,685.0,dark
168,13.58,2.58,2.69,24.5,105.0,1.55,0.84,0.39,1.54,8.660000,0.74,1.80,750.0,dark
169,13.40,4.60,2.86,25.0,112.0,1.98,0.96,0.27,1.11,8.500000,0.67,1.92,630.0,dark
171,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,dark
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.700000,0.62,1.71,660.0,dark
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.700000,0.64,1.74,740.0,dark
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.300000,0.70,1.56,750.0,dark
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.000000,0.59,1.56,835.0,dark
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.300000,0.60,1.62,840.0,dark
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.200000,0.61,1.60,560.0,dark

In [77]:
df.shape # the columns have increased by one since we have created the shade column

(178, 14)